name: .NET

on:
  push:
    branches: [ 'master', 'development' ]

defaults:
  run:
    working-directory: Ixian-LiteWallet

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Ixian-LiteWallet
      uses: actions/checkout@v4
      with:
        path: Ixian-LiteWallet

    - name: Checkout Ixian-Core
      uses: actions/checkout@v4
      with:
        repository: ixian-platform/Ixian-Core
        path: Ixian-Core
        ref: ${{ github.ref_name }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      working-directory: Ixian-LiteWallet/IxianLiteWallet
      run: dotnet restore

    - name: Building Ixian-LiteWallet
      working-directory: Ixian-LiteWallet/IxianLiteWallet
      run: dotnet build

    #- name: Running Unit Tests
    #  run: dotnet test UnitTests\bin\Debug\unittests.dll --verbosity normal
